### ISSUE TITLE
Clean up "Admin Console features" section

### ISSUE THREAD

**Issue by jbellis** [datastax/pulsar-docs#17]
This section contains super quick intro to admin consoles that are covered in more detail later on the page.  I suggest either hyperlinking the more detailed sections, or just eliminating this summary section as more confusing than helpful.

**Comment by mendonk** [comment]
Closing as completed https://github.com/datastax/pulsar-docs/blob/main/docs-src/luna-streaming-core/modules/ROOT/pages/admin-console-tutorial.adoc#features
