### ISSUE TITLE
Explain differences from Luna Streaming docker image and Apache Pulsar

### ISSUE THREAD

**Issue by nicoloboschi** [datastax/pulsar-docs#46]
It's important to explain to our users that Luna Streaming docker image is rootless. This means that the user that executes the VM processes is "pulsar" and not "root". 

We already document this distinction [here](https://github.com/datastax/release-notes/blob/master/Luna_Streaming_2.8_Release_Notes.md#upgrade-considerations-for-luna-streaming-distribution-280) but it's really coincise.

The big advantage is that root-less containers addresses [security concerns](https://blog.aquasec.com/rootless-containers-boosting-container-security), therefore it's valuable for the customer.

**Comment by michaeljmarshall** [comment]
We can add this documentation, but once my upstream changes are merged, I'd like to use the same solution in our docker image, too.

**Comment by nicoloboschi** [comment]
The differences will remain between Luna Streaming 2.8 and Apache Pulsar 2.8, which is the comparable ASF version.

We specify that Luna Streaming 2.8 is an enhanced version of Apache Pulsar 2.8.1 [here](https://docs.datastax.com/en/luna/streaming/2.8/index.html#_components)

**Comment by michaeljmarshall** [comment]
Sounds good. Thanks for clarifying.
